"""
MacroMate – Built-in Recipe Library
Pre-loaded recipes so users can generate meal plans immediately.
These recipes are returned when a user has no own recipes,
and can be used alongside user recipes for plan generation.
"""

from __future__ import annotations

BUILTIN_RECIPES: list[dict] = [
    # ── Frühstück ──
    {
        "name": "Overnight Oats mit Beeren",
        "description": "Cremige Haferflocken über Nacht eingeweicht mit frischen Beeren und Joghurt.",
        "instructions": "1. Haferflocken, Milch und Joghurt verrühren.\n2. In ein Glas füllen und über Nacht in den Kühlschrank stellen.\n3. Morgens mit Beeren, Honig und Chiasamen toppen.",
        "category": "vegetarisch",
        "meal_type": "frühstück",
        "calories": 380,
        "protein": 18,
        "fat": 10,
        "carbs": 55,
        "servings": 1,
        "ingredients": [
            {"name": "Haferflocken", "quantity": 60, "unit": "g"},
            {"name": "Milch", "quantity": 150, "unit": "ml"},
            {"name": "Joghurt", "quantity": 100, "unit": "g"},
            {"name": "Blaubeeren", "quantity": 50, "unit": "g"},
            {"name": "Honig", "quantity": 10, "unit": "g"},
            {"name": "Chiasamen", "quantity": 10, "unit": "g"},
        ],
    },
    {
        "name": "Protein-Rührei mit Vollkornbrot",
        "description": "Klassisches Rührei mit Tomaten und Vollkorntoast – perfekt für den Start in den Tag.",
        "instructions": "1. Eier verquirlen, salzen und pfeffern.\n2. In einer Pfanne mit etwas Butter stocken lassen.\n3. Tomaten dazugeben und mit Vollkornbrot servieren.",
        "category": "vegetarisch",
        "meal_type": "frühstück",
        "calories": 420,
        "protein": 28,
        "fat": 22,
        "carbs": 30,
        "servings": 1,
        "ingredients": [
            {"name": "Ei", "quantity": 3, "unit": "Stück"},
            {"name": "Vollkornbrot", "quantity": 2, "unit": "Scheibe"},
            {"name": "Tomate", "quantity": 1, "unit": "Stück"},
            {"name": "Butter", "quantity": 10, "unit": "g"},
        ],
    },
    {
        "name": "Skyr-Bowl mit Müsli",
        "description": "Proteinreiche Skyr-Bowl mit Knuspermüsli, Banane und Nüssen.",
        "instructions": "1. Skyr in eine Schüssel geben.\n2. Mit Müsli, Bananenscheiben und Walnüssen toppen.\n3. Optional mit Honig beträufeln.",
        "category": "vegetarisch",
        "meal_type": "frühstück",
        "calories": 350,
        "protein": 25,
        "fat": 9,
        "carbs": 45,
        "servings": 1,
        "ingredients": [
            {"name": "Skyr", "quantity": 200, "unit": "g"},
            {"name": "Müsli", "quantity": 40, "unit": "g"},
            {"name": "Banane", "quantity": 1, "unit": "Stück"},
            {"name": "Walnüsse", "quantity": 15, "unit": "g"},
        ],
    },
    {
        "name": "Vollkorn-Pancakes",
        "description": "Fluffige Vollkorn-Pancakes mit Ahornsirup und Beeren.",
        "instructions": "1. Mehl, Ei, Milch und Backpulver zu einem glatten Teig verrühren.\n2. In einer beschichteten Pfanne kleine Pancakes ausbacken.\n3. Mit Beeren und Ahornsirup servieren.",
        "category": "vegetarisch",
        "meal_type": "frühstück",
        "calories": 410,
        "protein": 15,
        "fat": 12,
        "carbs": 62,
        "servings": 1,
        "ingredients": [
            {"name": "Dinkelmehl", "quantity": 100, "unit": "g"},
            {"name": "Ei", "quantity": 1, "unit": "Stück"},
            {"name": "Milch", "quantity": 120, "unit": "ml"},
            {"name": "Backpulver", "quantity": 5, "unit": "g"},
            {"name": "Ahornsirup", "quantity": 20, "unit": "ml"},
            {"name": "Erdbeeren", "quantity": 50, "unit": "g"},
        ],
    },
    {
        "name": "Avocado-Toast mit Ei",
        "description": "Knuspriges Vollkornbrot mit cremiger Avocado und pochiertem Ei.",
        "instructions": "1. Avocado zerdrücken, mit Salz, Pfeffer und Zitronensaft würzen.\n2. Auf getoastetem Vollkornbrot verteilen.\n3. Mit pochiertem Ei und Chiliflocken toppen.",
        "category": "vegetarisch",
        "meal_type": "frühstück",
        "calories": 450,
        "protein": 20,
        "fat": 28,
        "carbs": 32,
        "servings": 1,
        "ingredients": [
            {"name": "Vollkornbrot", "quantity": 2, "unit": "Scheibe"},
            {"name": "Avocado", "quantity": 100, "unit": "g"},
            {"name": "Ei", "quantity": 2, "unit": "Stück"},
            {"name": "Zitrone", "quantity": 5, "unit": "ml"},
        ],
    },

    # ── Hauptgericht – Fleisch ──
    {
        "name": "Hähnchenbrust mit Reis und Brokkoli",
        "description": "Klassiker für Fitness-Ernährung: mageres Hähnchen, Vollkornreis und frischer Brokkoli.",
        "instructions": "1. Hähnchenbrust würzen und in der Pfanne goldbraun braten.\n2. Reis nach Anleitung kochen.\n3. Brokkoli dämpfen und zusammen servieren.",
        "category": "fleisch",
        "meal_type": "hauptgericht",
        "calories": 520,
        "protein": 45,
        "fat": 10,
        "carbs": 60,
        "servings": 1,
        "ingredients": [
            {"name": "Hähnchenbrust", "quantity": 200, "unit": "g"},
            {"name": "Reis", "quantity": 80, "unit": "g"},
            {"name": "Brokkoli", "quantity": 150, "unit": "g"},
            {"name": "Olivenöl", "quantity": 5, "unit": "ml"},
        ],
    },
    {
        "name": "Puten-Gemüse-Pfanne",
        "description": "Bunte Gemüsepfanne mit zartem Putenbruststreifen und Sojasoße.",
        "instructions": "1. Putenbrust in Streifen schneiden und anbraten.\n2. Paprika, Zucchini und Champignons hinzufügen.\n3. Mit Sojasoße ablöschen und mit Reis servieren.",
        "category": "fleisch",
        "meal_type": "hauptgericht",
        "calories": 450,
        "protein": 42,
        "fat": 12,
        "carbs": 40,
        "servings": 1,
        "ingredients": [
            {"name": "Putenbrust", "quantity": 200, "unit": "g"},
            {"name": "Paprika", "quantity": 100, "unit": "g"},
            {"name": "Zucchini", "quantity": 100, "unit": "g"},
            {"name": "Champignons", "quantity": 80, "unit": "g"},
            {"name": "Sojasoße", "quantity": 15, "unit": "ml"},
            {"name": "Reis", "quantity": 60, "unit": "g"},
        ],
    },
    {
        "name": "Rindfleisch-Bolognese mit Vollkornnudeln",
        "description": "Herzhafte Bolognese mit magerem Rinderhack und Vollkornpasta.",
        "instructions": "1. Hackfleisch anbraten, Zwiebel und Knoblauch hinzufügen.\n2. Tomatensoße einrühren und 20 Min köcheln lassen.\n3. Vollkornnudeln kochen und zusammen servieren.",
        "category": "fleisch",
        "meal_type": "hauptgericht",
        "calories": 580,
        "protein": 35,
        "fat": 18,
        "carbs": 70,
        "servings": 1,
        "ingredients": [
            {"name": "Rinderhackfleisch", "quantity": 150, "unit": "g"},
            {"name": "Vollkornnudeln", "quantity": 100, "unit": "g"},
            {"name": "Tomatensoße", "quantity": 150, "unit": "g"},
            {"name": "Zwiebel", "quantity": 1, "unit": "Stück"},
            {"name": "Knoblauch", "quantity": 2, "unit": "Stück"},
        ],
    },
    {
        "name": "Hähnchen-Wrap mit Salat",
        "description": "Leichter Wrap mit gegrilltem Hähnchen, Salat und Joghurt-Dressing.",
        "instructions": "1. Hähnchenbrust grillen und in Streifen schneiden.\n2. Wrap mit Salat, Tomate, Gurke und Hähnchen füllen.\n3. Joghurt-Dressing darüber geben und einrollen.",
        "category": "fleisch",
        "meal_type": "hauptgericht",
        "calories": 420,
        "protein": 35,
        "fat": 14,
        "carbs": 38,
        "servings": 1,
        "ingredients": [
            {"name": "Hähnchenbrust", "quantity": 150, "unit": "g"},
            {"name": "Tortilla Wrap", "quantity": 1, "unit": "Stück"},
            {"name": "Blattsalat", "quantity": 30, "unit": "g"},
            {"name": "Tomate", "quantity": 50, "unit": "g"},
            {"name": "Gurke", "quantity": 50, "unit": "g"},
            {"name": "Naturjoghurt", "quantity": 30, "unit": "g"},
        ],
    },

    # ── Hauptgericht – Fisch ──
    {
        "name": "Lachs mit Süßkartoffeln und Spinat",
        "description": "Omega-3-reicher Lachs mit gebackenen Süßkartoffeln und frischem Blattspinat.",
        "instructions": "1. Süßkartoffeln in Spalten schneiden und im Ofen backen (25 Min, 200°C).\n2. Lachs in der Pfanne 3-4 Min pro Seite braten.\n3. Spinat kurz anbraten und zusammen servieren.",
        "category": "fisch",
        "meal_type": "hauptgericht",
        "calories": 550,
        "protein": 38,
        "fat": 22,
        "carbs": 50,
        "servings": 1,
        "ingredients": [
            {"name": "Lachs", "quantity": 180, "unit": "g"},
            {"name": "Süßkartoffel", "quantity": 200, "unit": "g"},
            {"name": "Spinat", "quantity": 100, "unit": "g"},
            {"name": "Olivenöl", "quantity": 10, "unit": "ml"},
        ],
    },
    {
        "name": "Thunfisch-Salat Bowl",
        "description": "Proteinreiche Salatbowl mit Thunfisch, Ei und Avocado.",
        "instructions": "1. Blattsalat in eine Schüssel geben.\n2. Thunfisch abtropfen, Ei kochen und vierteln.\n3. Avocado, Tomate und Mais dazugeben, mit Dressing servieren.",
        "category": "fisch",
        "meal_type": "hauptgericht",
        "calories": 400,
        "protein": 35,
        "fat": 20,
        "carbs": 22,
        "servings": 1,
        "ingredients": [
            {"name": "Thunfisch (Dose)", "quantity": 120, "unit": "g"},
            {"name": "Blattsalat", "quantity": 80, "unit": "g"},
            {"name": "Ei", "quantity": 1, "unit": "Stück"},
            {"name": "Avocado", "quantity": 50, "unit": "g"},
            {"name": "Tomate", "quantity": 80, "unit": "g"},
            {"name": "Mais (Dose)", "quantity": 40, "unit": "g"},
        ],
    },

    # ── Hauptgericht – Vegetarisch ──
    {
        "name": "Gemüse-Curry mit Reis",
        "description": "Würziges Gemüsecurry mit Kokosmilch und Basmatireis.",
        "instructions": "1. Zwiebel und Knoblauch anbraten, Currypaste hinzufügen.\n2. Gemüse und Kokosmilch dazugeben, 15 Min köcheln.\n3. Mit Basmatireis servieren.",
        "category": "vegan",
        "meal_type": "hauptgericht",
        "calories": 480,
        "protein": 14,
        "fat": 18,
        "carbs": 68,
        "servings": 1,
        "ingredients": [
            {"name": "Karotten", "quantity": 100, "unit": "g"},
            {"name": "Paprika", "quantity": 80, "unit": "g"},
            {"name": "Kichererbsen (Dose)", "quantity": 100, "unit": "g"},
            {"name": "Kokosmilch", "quantity": 100, "unit": "ml"},
            {"name": "Basmati Reis", "quantity": 80, "unit": "g"},
            {"name": "Zwiebel", "quantity": 1, "unit": "Stück"},
        ],
    },
    {
        "name": "Linsen-Dal mit Naan",
        "description": "Cremiges indisches Linsengericht mit Gewürzen.",
        "instructions": "1. Rote Linsen waschen und mit Wasser kochen.\n2. Zwiebel, Knoblauch, Ingwer und Gewürze anbraten.\n3. Linsen dazugeben, pürieren und mit Naan servieren.",
        "category": "vegan",
        "meal_type": "hauptgericht",
        "calories": 450,
        "protein": 22,
        "fat": 8,
        "carbs": 72,
        "servings": 1,
        "ingredients": [
            {"name": "Linsen (rot)", "quantity": 100, "unit": "g"},
            {"name": "Zwiebel", "quantity": 1, "unit": "Stück"},
            {"name": "Knoblauch", "quantity": 2, "unit": "Stück"},
            {"name": "Tomatenmark", "quantity": 20, "unit": "g"},
            {"name": "Kokosmilch", "quantity": 80, "unit": "ml"},
        ],
    },
    {
        "name": "Pasta mit Pesto und Tomaten",
        "description": "Schnelle Pasta mit Basilikumpesto und frischen Kirschtomaten.",
        "instructions": "1. Nudeln al dente kochen.\n2. Kirschtomaten halbieren und kurz in Olivenöl anbraten.\n3. Nudeln mit Pesto und Tomaten vermengen, Parmesan darüber.",
        "category": "vegetarisch",
        "meal_type": "hauptgericht",
        "calories": 520,
        "protein": 18,
        "fat": 22,
        "carbs": 65,
        "servings": 1,
        "ingredients": [
            {"name": "Nudeln", "quantity": 100, "unit": "g"},
            {"name": "Pesto", "quantity": 30, "unit": "g"},
            {"name": "Tomate", "quantity": 100, "unit": "g"},
            {"name": "Parmesan", "quantity": 15, "unit": "g"},
        ],
    },
    {
        "name": "Quinoa-Bowl mit Gemüse",
        "description": "Bunte Quinoa-Bowl mit geröstetem Gemüse und Tahini-Dressing.",
        "instructions": "1. Quinoa nach Anleitung kochen.\n2. Gemüse im Ofen rösten (20 Min, 200°C).\n3. In einer Schüssel anrichten und mit Tahini-Dressing servieren.",
        "category": "vegan",
        "meal_type": "hauptgericht",
        "calories": 460,
        "protein": 16,
        "fat": 18,
        "carbs": 58,
        "servings": 1,
        "ingredients": [
            {"name": "Quinoa", "quantity": 80, "unit": "g"},
            {"name": "Zucchini", "quantity": 100, "unit": "g"},
            {"name": "Paprika", "quantity": 80, "unit": "g"},
            {"name": "Avocado", "quantity": 50, "unit": "g"},
            {"name": "Spinat", "quantity": 30, "unit": "g"},
        ],
    },
    {
        "name": "Tofu-Stir-Fry mit Reis",
        "description": "Knuspriger Tofu mit buntem Gemüse und Sojasoße.",
        "instructions": "1. Tofu würfeln und knusprig anbraten.\n2. Gemüse im Wok scharf anbraten.\n3. Mit Sojasoße ablöschen und mit Reis servieren.",
        "category": "vegan",
        "meal_type": "hauptgericht",
        "calories": 440,
        "protein": 22,
        "fat": 15,
        "carbs": 55,
        "servings": 1,
        "ingredients": [
            {"name": "Tofu", "quantity": 200, "unit": "g"},
            {"name": "Paprika", "quantity": 80, "unit": "g"},
            {"name": "Brokkoli", "quantity": 100, "unit": "g"},
            {"name": "Reis", "quantity": 80, "unit": "g"},
            {"name": "Sojasoße", "quantity": 20, "unit": "ml"},
        ],
    },

    # ── Snacks ──
    {
        "name": "Protein-Shake mit Banane",
        "description": "Schneller Proteinshake nach dem Training.",
        "instructions": "1. Alle Zutaten in einen Mixer geben.\n2. 30 Sekunden mixen bis cremig.\n3. Sofort genießen.",
        "category": "vegetarisch",
        "meal_type": "snack",
        "calories": 280,
        "protein": 30,
        "fat": 5,
        "carbs": 30,
        "servings": 1,
        "ingredients": [
            {"name": "Whey Protein", "quantity": 30, "unit": "g"},
            {"name": "Banane", "quantity": 1, "unit": "Stück"},
            {"name": "Milch", "quantity": 250, "unit": "ml"},
        ],
    },
    {
        "name": "Quark mit Obst und Nüssen",
        "description": "Proteinreicher Snack mit Magerquark, saisonalem Obst und Mandeln.",
        "instructions": "1. Quark in eine Schüssel geben.\n2. Mit Obst und Mandeln toppen.\n3. Optional Honig hinzufügen.",
        "category": "vegetarisch",
        "meal_type": "snack",
        "calories": 220,
        "protein": 22,
        "fat": 6,
        "carbs": 20,
        "servings": 1,
        "ingredients": [
            {"name": "Magerquark", "quantity": 150, "unit": "g"},
            {"name": "Erdbeeren", "quantity": 50, "unit": "g"},
            {"name": "Mandeln", "quantity": 15, "unit": "g"},
        ],
    },
    {
        "name": "Hummus mit Gemüsesticks",
        "description": "Cremiger Hummus mit knackigen Gemüsesticks.",
        "instructions": "1. Kichererbsen mit Tahini, Zitronensaft und Knoblauch pürieren.\n2. Gemüse in Sticks schneiden.\n3. Dippen und genießen.",
        "category": "vegan",
        "meal_type": "snack",
        "calories": 200,
        "protein": 8,
        "fat": 10,
        "carbs": 22,
        "servings": 1,
        "ingredients": [
            {"name": "Kichererbsen (Dose)", "quantity": 100, "unit": "g"},
            {"name": "Karotten", "quantity": 80, "unit": "g"},
            {"name": "Gurke", "quantity": 80, "unit": "g"},
            {"name": "Paprika", "quantity": 50, "unit": "g"},
        ],
    },
    {
        "name": "Apfel mit Erdnussbutter",
        "description": "Einfacher, sättigender Snack mit gesunden Fetten.",
        "instructions": "1. Apfel in Spalten schneiden.\n2. Mit Erdnussbutter bestreichen oder dippen.",
        "category": "vegan",
        "meal_type": "snack",
        "calories": 250,
        "protein": 7,
        "fat": 14,
        "carbs": 28,
        "servings": 1,
        "ingredients": [
            {"name": "Apfel", "quantity": 1, "unit": "Stück"},
            {"name": "Erdnussbutter", "quantity": 20, "unit": "g"},
        ],
    },

    # ── Dessert ──
    {
        "name": "Protein-Pudding",
        "description": "Cremiger Schokoladen-Protein-Pudding als gesundes Dessert.",
        "instructions": "1. Protein-Pulver mit Milch und etwas Stärke verrühren.\n2. Aufkochen lassen bis die Masse eindickt.\n3. In Schälchen füllen und kühlen.",
        "category": "vegetarisch",
        "meal_type": "dessert",
        "calories": 180,
        "protein": 25,
        "fat": 3,
        "carbs": 14,
        "servings": 1,
        "ingredients": [
            {"name": "Whey Protein", "quantity": 30, "unit": "g"},
            {"name": "Milch", "quantity": 200, "unit": "ml"},
        ],
    },
    # ── Zusätzliche Rezepte ──
    {
        "name": "Griechischer Joghurt mit Granola",
        "description": "Cremiger griechischer Joghurt mit knusprigem Granola und frischen Früchten.",
        "instructions": "1. Griechischen Joghurt in eine Schüssel geben.\n2. Mit Granola und geschnittenen Früchten toppen.\n3. Mit Honig beträufeln.",
        "category": "vegetarisch",
        "meal_type": "frühstück",
        "calories": 340,
        "protein": 22,
        "fat": 12,
        "carbs": 38,
        "servings": 1,
        "ingredients": [
            {"name": "Griechischer Joghurt", "quantity": 200, "unit": "g"},
            {"name": "Granola", "quantity": 40, "unit": "g"},
            {"name": "Honig", "quantity": 10, "unit": "g"},
            {"name": "Erdbeeren", "quantity": 50, "unit": "g"},
        ],
    },
    {
        "name": "Veganes Buddha Bowl",
        "description": "Buntes Bowl mit Quinoa, Kichererbsen, Avocado und Tahini-Dressing.",
        "instructions": "1. Quinoa kochen und abkühlen lassen.\n2. Kichererbsen abtropfen und mit Gewürzen im Ofen rösten.\n3. Avocado schneiden, Gemüse anrichten und Tahini-Dressing drüber geben.",
        "category": "vegan",
        "meal_type": "mittagessen",
        "calories": 520,
        "protein": 18,
        "fat": 22,
        "carbs": 62,
        "servings": 1,
        "ingredients": [
            {"name": "Quinoa", "quantity": 80, "unit": "g"},
            {"name": "Kichererbsen", "quantity": 120, "unit": "g"},
            {"name": "Avocado", "quantity": 80, "unit": "g"},
            {"name": "Gurke", "quantity": 50, "unit": "g"},
            {"name": "Tahini", "quantity": 15, "unit": "g"},
            {"name": "Zitronensaft", "quantity": 10, "unit": "ml"},
        ],
    },
    {
        "name": "Lachs mit Süßkartoffel",
        "description": "Gebratener Lachs mit Süßkartoffel-Püree und gedünstetem Spinat.",
        "instructions": "1. Süßkartoffel weich kochen und pürieren.\n2. Lachs in der Pfanne scharf anbraten.\n3. Spinat kurz andünsten und zusammen servieren.",
        "category": "fisch",
        "meal_type": "abendessen",
        "calories": 510,
        "protein": 38,
        "fat": 20,
        "carbs": 42,
        "servings": 1,
        "ingredients": [
            {"name": "Lachs", "quantity": 180, "unit": "g"},
            {"name": "Süßkartoffel", "quantity": 200, "unit": "g"},
            {"name": "Spinat", "quantity": 100, "unit": "g"},
            {"name": "Olivenöl", "quantity": 5, "unit": "ml"},
        ],
    },
    {
        "name": "Hähnchen-Gyros-Bowl",
        "description": "Würzige Hähnchen-Gyros-Streifen mit Reis, Tzatziki und frischem Salat.",
        "instructions": "1. Hähnchen in Streifen schneiden und mit Gyrosgewürz anbraten.\n2. Reis kochen.\n3. Mit Tzatziki, Salat und Tomaten anrichten.",
        "category": "fleisch",
        "meal_type": "mittagessen",
        "calories": 550,
        "protein": 42,
        "fat": 15,
        "carbs": 58,
        "servings": 1,
        "ingredients": [
            {"name": "Hähnchenbrust", "quantity": 200, "unit": "g"},
            {"name": "Reis", "quantity": 80, "unit": "g"},
            {"name": "Joghurt", "quantity": 50, "unit": "g"},
            {"name": "Gurke", "quantity": 50, "unit": "g"},
            {"name": "Tomate", "quantity": 80, "unit": "g"},
        ],
    },
    {
        "name": "Vegane Linsensuppe",
        "description": "Herzhafte rote Linsensuppe mit Kokosmilch und Kurkuma.",
        "instructions": "1. Zwiebel und Knoblauch anbraten.\n2. Linsen und Gemüsebrühe dazugeben.\n3. Kokosmilch und Gewürze hinzufügen, 20 Min kochen.",
        "category": "vegan",
        "meal_type": "mittagessen",
        "calories": 380,
        "protein": 20,
        "fat": 12,
        "carbs": 48,
        "servings": 2,
        "ingredients": [
            {"name": "Rote Linsen", "quantity": 150, "unit": "g"},
            {"name": "Kokosmilch", "quantity": 100, "unit": "ml"},
            {"name": "Zwiebel", "quantity": 1, "unit": "Stück"},
            {"name": "Knoblauch", "quantity": 2, "unit": "Stück"},
            {"name": "Kurkuma", "quantity": 5, "unit": "g"},
        ],
    },
    {
        "name": "Protein-Wrap mit Thunfisch",
        "description": "Vollkorn-Wrap gefüllt mit Thunfisch, Mais und Frischkäse.",
        "instructions": "1. Thunfisch abtropfen und mit Frischkäse mischen.\n2. Mais und Salat hinzufügen.\n3. Wrap befüllen und einrollen.",
        "category": "fisch",
        "meal_type": "mittagessen",
        "calories": 410,
        "protein": 35,
        "fat": 14,
        "carbs": 38,
        "servings": 1,
        "ingredients": [
            {"name": "Tortilla Wrap", "quantity": 1, "unit": "Stück"},
            {"name": "Thunfisch", "quantity": 120, "unit": "g"},
            {"name": "Frischkäse", "quantity": 30, "unit": "g"},
            {"name": "Mais", "quantity": 40, "unit": "g"},
            {"name": "Blattsalat", "quantity": 20, "unit": "g"},
        ],
    },
    {
        "name": "Steak mit Ofengemüse",
        "description": "Saftiges Rindersteak mit buntem Ofengemüse und Kräuterbutter.",
        "instructions": "1. Gemüse in Stücke schneiden und mit Öl im Ofen rösten (200°C, 25 Min).\n2. Steak scharf in der Pfanne anbraten.\n3. Mit Kräuterbutter servieren.",
        "category": "fleisch",
        "meal_type": "abendessen",
        "calories": 580,
        "protein": 45,
        "fat": 30,
        "carbs": 25,
        "servings": 1,
        "ingredients": [
            {"name": "Rindersteak", "quantity": 200, "unit": "g"},
            {"name": "Paprika", "quantity": 100, "unit": "g"},
            {"name": "Zucchini", "quantity": 100, "unit": "g"},
            {"name": "Süßkartoffel", "quantity": 100, "unit": "g"},
            {"name": "Butter", "quantity": 15, "unit": "g"},
        ],
    },
    {
        "name": "Tofu Teriyaki mit Jasminreis",
        "description": "Knuspriger Tofu in süß-salziger Teriyaki-Sauce mit duftendem Jasminreis.",
        "instructions": "1. Tofu in Würfel schneiden und knusprig anbraten.\n2. Teriyaki-Sauce hinzufügen und karamellisieren lassen.\n3. Mit Jasminreis und Sesam servieren.",
        "category": "vegan",
        "meal_type": "abendessen",
        "calories": 450,
        "protein": 22,
        "fat": 14,
        "carbs": 58,
        "servings": 1,
        "ingredients": [
            {"name": "Tofu", "quantity": 200, "unit": "g"},
            {"name": "Reis", "quantity": 80, "unit": "g"},
            {"name": "Sojasoße", "quantity": 20, "unit": "ml"},
            {"name": "Honig", "quantity": 15, "unit": "g"},
            {"name": "Sesam", "quantity": 5, "unit": "g"},
        ],
    },
    {
        "name": "Protein-Flammkuchen",
        "description": "Dünner Flammkuchen mit Quark-Basis, Speck und Zwiebeln.",
        "instructions": "1. Teig dünn ausrollen und mit Schmand bestreichen.\n2. Zwiebeln und Speck darauf verteilen.\n3. Bei 220°C ca. 12 Minuten backen.",
        "category": "fleisch",
        "meal_type": "abendessen",
        "calories": 480,
        "protein": 28,
        "fat": 18,
        "carbs": 52,
        "servings": 1,
        "ingredients": [
            {"name": "Dinkelmehl", "quantity": 100, "unit": "g"},
            {"name": "Schmand", "quantity": 80, "unit": "g"},
            {"name": "Speck", "quantity": 60, "unit": "g"},
            {"name": "Zwiebel", "quantity": 1, "unit": "Stück"},
        ],
    },
    {
        "name": "Garnelen-Pasta",
        "description": "Spaghetti mit Knoblauch-Garnelen in Weißwein-Tomaten-Sauce.",
        "instructions": "1. Spaghetti al dente kochen.\n2. Garnelen mit Knoblauch und Chiliflocken anbraten.\n3. Tomaten und einen Schuss Weißwein dazugeben, mit Pasta vermengen.",
        "category": "fisch",
        "meal_type": "abendessen",
        "calories": 520,
        "protein": 32,
        "fat": 14,
        "carbs": 62,
        "servings": 1,
        "ingredients": [
            {"name": "Spaghetti", "quantity": 100, "unit": "g"},
            {"name": "Garnelen", "quantity": 150, "unit": "g"},
            {"name": "Knoblauch", "quantity": 2, "unit": "Stück"},
            {"name": "Kirschtomaten", "quantity": 100, "unit": "g"},
            {"name": "Olivenöl", "quantity": 10, "unit": "ml"},
        ],
    },
    {
        "name": "Veganer Burrito Bowl",
        "description": "Mexikanisch inspirierte Bowl mit schwarzen Bohnen, Reis und Guacamole.",
        "instructions": "1. Reis kochen und mit Limettensaft verfeinern.\n2. Bohnen erwärmen und würzen.\n3. Mit Guacamole, Salsa und Mais anrichten.",
        "category": "vegan",
        "meal_type": "mittagessen",
        "calories": 480,
        "protein": 16,
        "fat": 15,
        "carbs": 70,
        "servings": 1,
        "ingredients": [
            {"name": "Reis", "quantity": 80, "unit": "g"},
            {"name": "Schwarze Bohnen", "quantity": 120, "unit": "g"},
            {"name": "Avocado", "quantity": 60, "unit": "g"},
            {"name": "Mais", "quantity": 50, "unit": "g"},
            {"name": "Tomate", "quantity": 50, "unit": "g"},
            {"name": "Limette", "quantity": 10, "unit": "ml"},
        ],
    },
    {
        "name": "Putenbrust-Salat mit Feta",
        "description": "Leichter Salat mit gebratener Putenbrust, Feta und Honig-Senf-Dressing.",
        "instructions": "1. Putenbrust würzen und in der Pfanne braten.\n2. Salat waschen, Tomaten und Gurke schneiden.\n3. Feta darüber bröckeln und mit Dressing anmachen.",
        "category": "fleisch",
        "meal_type": "mittagessen",
        "calories": 380,
        "protein": 38,
        "fat": 18,
        "carbs": 15,
        "servings": 1,
        "ingredients": [
            {"name": "Putenbrust", "quantity": 180, "unit": "g"},
            {"name": "Blattsalat", "quantity": 80, "unit": "g"},
            {"name": "Feta", "quantity": 40, "unit": "g"},
            {"name": "Tomate", "quantity": 60, "unit": "g"},
            {"name": "Gurke", "quantity": 60, "unit": "g"},
        ],
    },
    {
        "name": "Smoothie Bowl Tropical",
        "description": "Erfrischende Smoothie Bowl mit Mango, Ananas und Kokos.",
        "instructions": "1. Gefrorene Mango und Banane mit Kokosmilch pürieren.\n2. In eine Schüssel geben.\n3. Mit Kokosflocken, Granola und Ananasstücken toppen.",
        "category": "vegan",
        "meal_type": "frühstück",
        "calories": 320,
        "protein": 8,
        "fat": 10,
        "carbs": 52,
        "servings": 1,
        "ingredients": [
            {"name": "Mango", "quantity": 120, "unit": "g"},
            {"name": "Banane", "quantity": 1, "unit": "Stück"},
            {"name": "Kokosmilch", "quantity": 80, "unit": "ml"},
            {"name": "Granola", "quantity": 30, "unit": "g"},
            {"name": "Kokosflocken", "quantity": 10, "unit": "g"},
        ],
    },
    {
        "name": "Hackfleisch-Chili con Carne",
        "description": "Würziges Chili con Carne mit Kidneybohnen und Mais.",
        "instructions": "1. Hackfleisch kräftig anbraten.\n2. Zwiebel, Knoblauch und Paprika dazugeben.\n3. Tomaten, Bohnen und Mais hinzufügen, 30 Min köcheln lassen.",
        "category": "fleisch",
        "meal_type": "abendessen",
        "calories": 560,
        "protein": 38,
        "fat": 22,
        "carbs": 48,
        "servings": 2,
        "ingredients": [
            {"name": "Rinderhackfleisch", "quantity": 250, "unit": "g"},
            {"name": "Kidneybohnen", "quantity": 150, "unit": "g"},
            {"name": "Mais", "quantity": 80, "unit": "g"},
            {"name": "Tomatensoße", "quantity": 200, "unit": "g"},
            {"name": "Zwiebel", "quantity": 1, "unit": "Stück"},
            {"name": "Paprika", "quantity": 1, "unit": "Stück"},
        ],
    },
    {
        "name": "Omelett mit Spinat und Käse",
        "description": "Fluffiges Omelett gefüllt mit frischem Spinat und geschmolzenem Käse.",
        "instructions": "1. Eier verquirlen und würzen.\n2. In einer Pfanne stocken lassen.\n3. Spinat und Käse auf eine Hälfte geben und zuklappen.",
        "category": "vegetarisch",
        "meal_type": "frühstück",
        "calories": 350,
        "protein": 26,
        "fat": 24,
        "carbs": 6,
        "servings": 1,
        "ingredients": [
            {"name": "Ei", "quantity": 3, "unit": "Stück"},
            {"name": "Spinat", "quantity": 60, "unit": "g"},
            {"name": "Käse", "quantity": 30, "unit": "g"},
            {"name": "Butter", "quantity": 5, "unit": "g"},
        ],
    },
    {
        "name": "Asiatische Gemüse-Nudeln",
        "description": "Schnelle Reisnudeln mit knackigem Gemüse und Erdnuss-Sauce.",
        "instructions": "1. Reisnudeln nach Packung kochen.\n2. Gemüse im Wok scharf anbraten.\n3. Erdnuss-Sauce und Nudeln dazugeben, vermengen.",
        "category": "vegan",
        "meal_type": "abendessen",
        "calories": 420,
        "protein": 14,
        "fat": 16,
        "carbs": 56,
        "servings": 1,
        "ingredients": [
            {"name": "Reisnudeln", "quantity": 100, "unit": "g"},
            {"name": "Paprika", "quantity": 60, "unit": "g"},
            {"name": "Karotte", "quantity": 60, "unit": "g"},
            {"name": "Erdnussbutter", "quantity": 25, "unit": "g"},
            {"name": "Sojasoße", "quantity": 15, "unit": "ml"},
        ],
    },
    {
        "name": "Mediterraner Couscous-Salat",
        "description": "Frischer Couscous-Salat mit getrockneten Tomaten, Oliven und Feta.",
        "instructions": "1. Couscous mit heißem Wasser aufquellen lassen.\n2. Tomaten, Oliven, Gurke und Feta klein schneiden.\n3. Alles vermengen und mit Olivenöl und Zitrone abschmecken.",
        "category": "vegetarisch",
        "meal_type": "mittagessen",
        "calories": 400,
        "protein": 14,
        "fat": 16,
        "carbs": 50,
        "servings": 1,
        "ingredients": [
            {"name": "Couscous", "quantity": 80, "unit": "g"},
            {"name": "Feta", "quantity": 40, "unit": "g"},
            {"name": "Oliven", "quantity": 30, "unit": "g"},
            {"name": "Getrocknete Tomaten", "quantity": 30, "unit": "g"},
            {"name": "Gurke", "quantity": 60, "unit": "g"},
        ],
    },
    {
        "name": "Power-Porridge mit Nüssen",
        "description": "Warmer Haferbrei mit Mandeln, Zimt und Beerenmix.",
        "instructions": "1. Haferflocken mit Milch aufkochen.\n2. Bei niedriger Hitze cremig rühren.\n3. Mit Mandeln, Beeren und Zimt servieren.",
        "category": "vegetarisch",
        "meal_type": "frühstück",
        "calories": 400,
        "protein": 16,
        "fat": 14,
        "carbs": 52,
        "servings": 1,
        "ingredients": [
            {"name": "Haferflocken", "quantity": 70, "unit": "g"},
            {"name": "Milch", "quantity": 200, "unit": "ml"},
            {"name": "Mandeln", "quantity": 20, "unit": "g"},
            {"name": "Beeren-Mix", "quantity": 50, "unit": "g"},
            {"name": "Zimt", "quantity": 2, "unit": "g"},
        ],
    },
    {
        "name": "Fischstäbchen mit Kartoffelpüree",
        "description": "Knusprige Fischstäbchen mit cremigem Kartoffelpüree und Erbsen.",
        "instructions": "1. Kartoffeln kochen und pürieren.\n2. Fischstäbchen im Ofen oder Pfanne zubereiten.\n3. Mit Erbsen servieren.",
        "category": "fisch",
        "meal_type": "abendessen",
        "calories": 480,
        "protein": 25,
        "fat": 18,
        "carbs": 55,
        "servings": 1,
        "ingredients": [
            {"name": "Fischstäbchen", "quantity": 6, "unit": "Stück"},
            {"name": "Kartoffeln", "quantity": 250, "unit": "g"},
            {"name": "Milch", "quantity": 50, "unit": "ml"},
            {"name": "Butter", "quantity": 10, "unit": "g"},
            {"name": "Erbsen", "quantity": 80, "unit": "g"},
        ],
    },
    {
        "name": "Protein-Quark mit Früchten",
        "description": "Eiweißreicher Magerquark mit Obst und einem Schuss Honig.",
        "instructions": "1. Magerquark cremig rühren.\n2. Mit Beeren und Bananenstücken toppen.\n3. Honig drüber geben.",
        "category": "vegetarisch",
        "meal_type": "snack",
        "calories": 220,
        "protein": 30,
        "fat": 2,
        "carbs": 22,
        "servings": 1,
        "ingredients": [
            {"name": "Magerquark", "quantity": 250, "unit": "g"},
            {"name": "Blaubeeren", "quantity": 50, "unit": "g"},
            {"name": "Banane", "quantity": 0.5, "unit": "Stück"},
            {"name": "Honig", "quantity": 10, "unit": "g"},
        ],
    },
    {
        "name": "Kichererbsen-Curry",
        "description": "Cremiges veganes Curry mit Kichererbsen, Kokosmilch und Basmatireis.",
        "instructions": "1. Zwiebel und Knoblauch anbraten, Currypaste dazugeben.\n2. Kichererbsen und Kokosmilch hinzufügen.\n3. 15 Min köcheln lassen und mit Reis servieren.",
        "category": "vegan",
        "meal_type": "abendessen",
        "calories": 490,
        "protein": 18,
        "fat": 18,
        "carbs": 62,
        "servings": 1,
        "ingredients": [
            {"name": "Kichererbsen", "quantity": 200, "unit": "g"},
            {"name": "Kokosmilch", "quantity": 100, "unit": "ml"},
            {"name": "Reis", "quantity": 80, "unit": "g"},
            {"name": "Currypaste", "quantity": 15, "unit": "g"},
            {"name": "Zwiebel", "quantity": 1, "unit": "Stück"},
        ],
    },
    {
        "name": "Schnitzel mit Kartoffelsalat",
        "description": "Klassisches paniertes Schweineschnitzel mit Kartoffelsalat.",
        "instructions": "1. Schnitzel panieren (Mehl, Ei, Semmelbrösel).\n2. In Butterschmalz goldbraun braten.\n3. Kartoffelsalat vorbereiten und zusammen servieren.",
        "category": "fleisch",
        "meal_type": "abendessen",
        "calories": 620,
        "protein": 35,
        "fat": 28,
        "carbs": 55,
        "servings": 1,
        "ingredients": [
            {"name": "Schweineschnitzel", "quantity": 180, "unit": "g"},
            {"name": "Kartoffeln", "quantity": 200, "unit": "g"},
            {"name": "Semmelbrösel", "quantity": 40, "unit": "g"},
            {"name": "Ei", "quantity": 1, "unit": "Stück"},
        ],
    },
    {
        "name": "Energiebällchen",
        "description": "Gesunde Energiekugeln aus Datteln, Haferflocken und Kakao.",
        "instructions": "1. Datteln, Haferflocken und Kakao im Mixer zerkleinern.\n2. Erdnussbutter dazugeben.\n3. Kugeln formen und kalt stellen.",
        "category": "vegan",
        "meal_type": "snack",
        "calories": 190,
        "protein": 6,
        "fat": 8,
        "carbs": 26,
        "servings": 4,
        "ingredients": [
            {"name": "Datteln", "quantity": 100, "unit": "g"},
            {"name": "Haferflocken", "quantity": 50, "unit": "g"},
            {"name": "Kakao", "quantity": 10, "unit": "g"},
            {"name": "Erdnussbutter", "quantity": 20, "unit": "g"},
        ],
    },
]


def get_builtin_recipes() -> list[dict]:
    """Return all built-in recipes."""
    return BUILTIN_RECIPES


def get_builtin_recipes_for_generation(
    categories: list[str] | None = None,
    diet_type: str | None = None,
    allergies: list[str] | None = None,
) -> list[dict]:
    """
    Return built-in recipes filtered by user preferences.
    Used for meal plan generation when user has no own recipes.
    """
    results = list(BUILTIN_RECIPES)

    if categories:
        results = [r for r in results if r["category"] in categories]

    if diet_type and diet_type != "keine":
        diet_map = {
            "vegan": ["vegan"],
            "vegetarisch": ["vegan", "vegetarisch"],
            "pescetarisch": ["vegan", "vegetarisch", "fisch"],
        }
        allowed = diet_map.get(diet_type, None)
        if allowed:
            results = [r for r in results if r["category"] in allowed]

    # Basic allergy filtering (by ingredient names)
    if allergies:
        allergen_ingredient_map = {
            "gluten": ["mehl", "nudeln", "spaghetti", "brot", "toast", "wrap", "tortilla", "couscous", "bulgur", "seitan", "haferflocken", "müsli", "dinkelmehl", "vollkornnudeln", "vollkornbrot", "knäckebrot", "pancake"],
            "laktose": ["milch", "joghurt", "quark", "käse", "sahne", "butter", "mozzarella", "parmesan", "feta", "skyr", "whey"],
            "nüsse": ["mandeln", "walnüsse", "cashews", "erdnussbutter", "pesto", "nüsse", "mandelmilch", "mandelmehl"],
            "erdnüsse": ["erdnüsse", "erdnussbutter"],
            "soja": ["sojasoße", "tofu", "tempeh", "edamame", "sojamilch"],
            "ei": ["ei", "eier", "eiweiß"],
            "fisch": ["lachs", "thunfisch", "kabeljau", "forelle", "hering", "pangasius"],
            "schalentiere": ["garnelen", "krabben", "muscheln"],
        }

        def contains_allergen(recipe: dict, allergy: str) -> bool:
            bad_ingredients = allergen_ingredient_map.get(allergy, [])
            if not bad_ingredients:
                return False
            for ing in recipe.get("ingredients", []):
                ing_name = ing["name"].lower()
                for bad in bad_ingredients:
                    if bad in ing_name:
                        return True
            return False

        for allergy in allergies:
            results = [r for r in results if not contains_allergen(r, allergy)]

    return results
